export const selectedCities = [
  "100 mile house",
  "bagot",
  "bickerton west",
  "brookside.",
  "carseland",
  "codys",
  "delaware",
  "edwards",
  "fort kent",
  "gouldtown",
  "havre-aux-maisons",
  "irvine",
  "kugaaruk",
  "lefaivre",
  "mackay siding",
  "membertou",
  "mulhurst bay",
  "notre-dame-de-lorette",
  "peterborough",
  "pratt",
  "robb",
  "saint-edouard-de-maskinonge",
  "saint-stanislas",
  "seeleys bay",
  "spy hill",
  "sussex east",
  "upper brighton",
  "watino",
  "wyevale",
];
